### ISSUE TITLE
'CALL_EXCEPTION' when buying token

### ISSUE THREAD

**Issue by camillecorti** [austinjblake/encode-week-3#1]
$ yarn run ts-node ./scripts/BuyToken.ts 0xd6CD9823d1b9a8F215Fc0230FF712CbA57c53d40 0.0001

Working on Goerli Testnet connected to wallet 0xfC4F626a3dfa723E4b501FeE03D1eC5f9f55dcE4 with balance of 48731437108462884
Account 0xfC4F626a3dfa723E4b501FeE03D1eC5f9f55dcE4 currently has 0 G5 tokens
Buying ERC20voting token...
Error: missing revert data in call exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (code=CALL_EXCEPTION, version=providers/5.4.5)
    at Logger.makeError (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at /home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:631:24
    at Array.forEach (<anonymous>)
    at /home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:613:33
    at step (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/providers/lib/fallback-provider.js:48:23)
    at Object.next (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
    at step (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/providers/lib/fallback-provider.js:33:139)
    at Object.next (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/providers/lib/fallback-provider.js:29:53)
    at fulfilled (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/providers/lib/fallback-provider.js:20:58) {
  reason: 'missing revert data in call exception',
  code: 'CALL_EXCEPTION'
}

**Comment by camillecorti** [comment]
first time i ran script i got the following error, so i edited the .env and added my etherscan API

$ yarn run ts-node ./scripts/BuyToken.ts 0xd6CD9823d1b9a8F215Fc0230FF712CbA57c53d40 0.0001

Error: invalid hexlify value (argument="value", value="<c534b621be75bfcd0e661448163aa277f1d457472156db770f3798edb4348f6e>", code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at Logger.makeError (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at hexlify (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/bytes/src.ts/index.ts:252:19)
    at new SigningKey (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/signing-key/src.ts/index.ts:35:51)
    at new Wallet (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/@ethersproject/wallet/src.ts/index.ts:89:36)
    at deploy (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/scripts/BuyToken.ts:13:18)
    at Object.<anonymous> (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/scripts/BuyToken.ts:36:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/home/camillionaire/Desktop/Bootcamp/Project3/encode-week-3/node_modules/ts-node/src/index.ts:1618:23) {
  reason: 'invalid hexlify value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '<c534b621be75bfcd0e661448163aa277f1d457472156db770f3798edb4348f6e>'
}
